 
@startuml
@startgantt
Project starts 2024-09-26

[Requirements] as [RE] happens on 2024-10-03 and is colored in hotpink
[Formulate questions for meet] happens on 2024-10-03 and is colored in hotpink
then [Requirements Elicitation] happens 2024-10-10 and is colored in hotpink
then [Requirements Report] on {James, Laina, Mansi} starts 2024-10-14 and is colored in hotpink
[Requirements Report] ends on 2024-10-25
[RE] ends at [Requirements Report]'s end

[Risk Assessment and Mitigation Report] as [RI] starts 2024-10-07 and is colored in greenyellow
[Draft risk management process] on {Almira, James} starts on 2024-10-14 and ends at 2024-10-24 and is colored in greenyellow
[Create risk register] on {Almira, Mansi} starts at 2024-10-14 and ends at 2024-10-17 and is colored in greenyellow
[RI] ends at [Draft risk management process]'s end

[Method Selection and Planning] as [P] starts 2024-10-17 and is colored in orange
[Method Selection write-up] on {Harry,Almira} starts at 2024-10-17 and ends at 2024-10-20 and is colored in orange
[Planning write-up] on {Mansi} starts at 2024-10-24 and ends at 2024-11-06 and is colored in orange
[P] ends at [Planning write-up]'s end

[Implementation] happens at 2024-10-14 and is colored in deepskyblue/dodgerblue
[Add Stretch Viewport] on {Harry} starts at 2024-10-15 and is colored in deepskyblue/dodgerblue
then [Update map and add textures] on {Harry} starts at 2024-10-25 and is colored in deepskyblue/dodgerblue
then [Add ability to build] on {Harry} starts at 2024-10-25 and ends at 2024-11-04 and is colored in deepskyblue/dodgerblue
then [Work on UI (Timer, Building Counter, End Screen] on {James} starts at 2024-11-04 and lasts 3 day and is colored in deepskyblue/dodgerblue
then [Work on bugs/add remaining requirements] ends at 2024-11-09 and is colored in deepskyblue
[Implementation] ends at [Work on bugs/add remaining requirements]'s end

[Architecture] as [A] happens on 2024-10-20 and is colored in yellow
[Initial Architecture write-up] on {Vadim} starts 2024-10-20 and ends 2024-10-25 and is colored in yellow
[Reiteration of architecture] on {Vadim} starts at [Add ability to build]'s end and ends 2024-11-07 and is colored in yellow
then [Add architecture to the website] on {Vadim} starts on 2024-11-07 and is colored in darkturquoise
[A] ends at [Reiteration of architecture]'s end

[Website] as [W] happens at 2024-10-03 and is colored in darkturquoise
[Develop website] on {Vadim} starts on 2024-10-03 and ends on 2024-10-10 and is colored in darkturquoise
then [Link deliverables on website] on {Vadim} starts on 2024-10-17 and is colored in darkturquoise
[Incorporate final weekly updates on website] on {Mansi} starts on 2024-10-24 and ends on 2024-11-05 and is colored in darkturquoise
[W] ends at [Add architecture to the website]'s end


@endgantt
@enduml


