@startgantt
Project starts 2024-09-26

[Requirements] as [RE] happens on 2024-10-03 and is colored in hotpink
[Formulate questions for meet] happens on 2024-10-03 and is colored in hotpink
then [Requirements Elicitation] happens 2024-10-10 and is colored in hotpink
then [Requirements Report] on {James, Laina, Mansi} starts 2024-10-14 and is colored in hotpink
[Requirements Report] ends on 2024-10-20
[RE] ends at [Requirements Report]'s end

[Risk Assessment and Mitigation Report] as [RI] happens at 2024-10-07 and is colored in greenyellow
[Draft risk management process] on {Almira, James} starts on 2024-10-07 and ends at 2024-10-20 and is colored in greenyellow
[Create risk register] on {Almira, Mansi} starts at 2024-10-14 and ends at 2024-10-17 and is colored in greenyellow
[RI] ends at [Draft risk management process]'s end

[Method Selection and Planning] as [P] happens 2024-10-14 and is colored in orange
[Method Selection write-up] starts at 2024-10-14 and ends at 2024-10-21 and is colored in orange
[Planning write-up] starts at 2024-10-14 and ends at 2024-10-28 and is colored in orange
[Post weekly updates] on {Mansi} starts at [Planning write-up]'s start and requires 5 days and is colored in darkturquoise
[P] ends at [Planning write-up]'s end

[Implementation] happens at 2024-10-14 and is colored in deepskyblue/dodgerblue
then [Architecture] as [A] is colored in yellow
then [Initial Architecture] starts at [A]'s start and is colored in yellow

[Website] as [W] happens 2024-10-03 and is colored in darkturquoise
[Develop website] on {Vadim} starts on 2024-10-10 and is colored in darkturquoise
then [Add hyperlinks] on {Vadim} starts on 2024-10-14 and requires 1 day and is colored in darkturquoise
[W] ends at [Post weekly updates]'s end

@endgantt

